version: "3.8"
services:
  redis:
    restart: always
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - "/.storage/redis_data:/data"

  postgresql:
    image: postgres:latest
    env:
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    volumes:
      - ./.github/workflows:/docker-entrypoint-initdb.d